apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-metrics-reader"
rules:
- apiGroups: [""]
  resources: ["nodes/stats"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
