syntax = "proto3";
package metrics;

option go_package = "../gen";

service MetricsScraper {
  rpc StreamMetrics(stream NodeSnapshot) returns (Ack);
}

message NodeSnapshot {
  string node_name = 1;
  double cpu_percent = 2;
  uint64 mem_used = 3;
  uint64 mem_total = 4;
  int64 timestamp = 5;
  repeated ContainerMetrics containers = 6;
}

message ContainerMetrics {
  // metadata
  string namespace = 1;
  string pod_name = 2;
  string container_name = 3;

  // raw
  double cpu_usage_seconds = 4;
  double cpu_throttled_ratio = 5;
  uint64 mem_wss = 6;
  uint64 mem_rss = 7;
  uint64 oom_events = 8;

  // cpu rate
  double cpu_rate = 9;

  // utilizaiton
  double cpu_utilization = 10;
  double mem_utilization = 11;

  // k8s resource spec
  ResourceSpec limits = 12;
  ResourceSpec requests = 13;

  // utilizaiton history
  repeated double cpu_utilization_history = 14;
  repeated double mem_utilization_history = 15;
}

message ResourceSpec {
  int64 cpu_millis = 1;
  int64 memory_bytes = 2;
}

message Ack {
  bool ok = 1;
}
